package main.support;

import java.util.ArrayList;
import java.util.List;

public class InstrumentLocalisation {

    private static List<String> instrumentNamesRU;
    private static List<String> instrumentNamesENG;
    static {
        instrumentNamesRU = new ArrayList<>();
        instrumentNamesRU.add("");
        instrumentNamesRU.add("Акустический рояль");
        instrumentNamesRU.add("Яркий рояль");
        instrumentNamesRU.add("Большой рояль");
        instrumentNamesRU.add("\"Разбитной\" рояль");
        instrumentNamesRU.add("Электропианино Родес");
        instrumentNamesRU.add("Электропианино Хорес");
        instrumentNamesRU.add("Клавесин");
        instrumentNamesRU.add("Клавинет");
        instrumentNamesRU.add("Челеста");
        instrumentNamesRU.add("Колокольчики");
        instrumentNamesRU.add("Музыкальная шкатулка");
        instrumentNamesRU.add("Вибрафон");
        instrumentNamesRU.add("Маримба");
        instrumentNamesRU.add("Ксилофон");
        instrumentNamesRU.add("Колокола");
        instrumentNamesRU.add("Цимбалы");
        instrumentNamesRU.add("Орган Хаммонда");
        instrumentNamesRU.add("Перкуссионный электроорган");
        instrumentNamesRU.add("Рок орган");
        instrumentNamesRU.add("Кафедральный орган");
        instrumentNamesRU.add("Язычковый орган");
        instrumentNamesRU.add("Аккордеон");
        instrumentNamesRU.add("Гармоника");
        instrumentNamesRU.add("Аккордеон танго");
        instrumentNamesRU.add("Акустическая гитара нейлон");
        instrumentNamesRU.add("Акустическая гитара металл");
        instrumentNamesRU.add("Джазовая электрогитара");
        instrumentNamesRU.add("Чистая электрогитара");
        instrumentNamesRU.add("Приглушенная электрогитара");
        instrumentNamesRU.add("Овердрайв гитара");
        instrumentNamesRU.add("Дисторшен гитара");
        instrumentNamesRU.add("Гитарные гармоники");
        instrumentNamesRU.add("Акустический бас");
        instrumentNamesRU.add("Пальцевый бас");
        instrumentNamesRU.add("Щипковый бас");
        instrumentNamesRU.add("Безладовый бас");
        instrumentNamesRU.add("Слэп бас - 1");
        instrumentNamesRU.add("Слэп бас - 2");
        instrumentNamesRU.add("Синтетический бас - 1");
        instrumentNamesRU.add("Синтетический бас - 2");
        instrumentNamesRU.add("Скрипка");
        instrumentNamesRU.add("Альт");
        instrumentNamesRU.add("Виолончель");
        instrumentNamesRU.add("Контрабас");
        instrumentNamesRU.add("Тремоло струнных");
        instrumentNamesRU.add("Пиццикато струнных");
        instrumentNamesRU.add("Арфа");
        instrumentNamesRU.add("Литавры");
        instrumentNamesRU.add("Ансамбль струнных - 1");
        instrumentNamesRU.add("Ансамбль струнных - 2");
        instrumentNamesRU.add("Синтетические струнные - 1");
        instrumentNamesRU.add("синтетические струнные  - 2");
        instrumentNamesRU.add("Хор \"А\"");
        instrumentNamesRU.add("Голос \"О\"");
        instrumentNamesRU.add("Синтетический голос");
        instrumentNamesRU.add("Оркестровое тутти");
        instrumentNamesRU.add("Труба");
        instrumentNamesRU.add("Тромбон");
        instrumentNamesRU.add("Туба");
        instrumentNamesRU.add("Труба с сурдиной");
        instrumentNamesRU.add("Валторна");
        instrumentNamesRU.add("Медная секция");
        instrumentNamesRU.add("Синтетическая медь - 1");
        instrumentNamesRU.add("Синтетическая медь - 2");
        instrumentNamesRU.add("Саксофон сопрано");
        instrumentNamesRU.add("Саксофон альт");
        instrumentNamesRU.add("Саксофон тенор");
        instrumentNamesRU.add("Саксофон баритон");
        instrumentNamesRU.add("Гобой");
        instrumentNamesRU.add("Английский рожок");
        instrumentNamesRU.add("Фагот");
        instrumentNamesRU.add("Кларнет");
        instrumentNamesRU.add("Флейта пикколо");
        instrumentNamesRU.add("Флейта");
        instrumentNamesRU.add("Рекордер");
        instrumentNamesRU.add("Пан-флейта");
        instrumentNamesRU.add("Бутылочная флейта");
        instrumentNamesRU.add("Сякухати");
        instrumentNamesRU.add("Свист");
        instrumentNamesRU.add("Окарина");
        instrumentNamesRU.add("Соло прямоугольная волна");
        instrumentNamesRU.add("Соло пилообразная волна");
        instrumentNamesRU.add("Соло калиопе");
        instrumentNamesRU.add("Соло чиф");
        instrumentNamesRU.add("Соло чаранг");
        instrumentNamesRU.add("Синтетический голос соло");
        instrumentNamesRU.add("Яркий пилообразный сигнал");
        instrumentNamesRU.add("Бас + соло");
        instrumentNamesRU.add("Фантазия");
        instrumentNamesRU.add("Накладка теплая");
        instrumentNamesRU.add("Накладка полисинтезатор");
        instrumentNamesRU.add("Накладка космическая");
        instrumentNamesRU.add("Накладка смычковая");
        instrumentNamesRU.add("Накладка металл");
        instrumentNamesRU.add("Накладка хало");
        instrumentNamesRU.add("Накладка изгиб");
        instrumentNamesRU.add("Ледяной дождь");
        instrumentNamesRU.add("Саундтрек");
        instrumentNamesRU.add("Кристалл");
        instrumentNamesRU.add("Атмосфера");
        instrumentNamesRU.add("Яркость");
        instrumentNamesRU.add("Гоблин");
        instrumentNamesRU.add("Эхо");
        instrumentNamesRU.add("Звезда");
        instrumentNamesRU.add("Ситара");
        instrumentNamesRU.add("Банджо");
        instrumentNamesRU.add("Сямисен");
        instrumentNamesRU.add("Кото");
        instrumentNamesRU.add("Калимба");
        instrumentNamesRU.add("Волынка");
        instrumentNamesRU.add("Уличная скрипка");
        instrumentNamesRU.add("Санай");
        instrumentNamesRU.add("Звон колокольчика");
        instrumentNamesRU.add("Агого");
        instrumentNamesRU.add("Стальные барабаны");
        instrumentNamesRU.add("Деревянная коробочка");
        instrumentNamesRU.add("Барабан тайко");
        instrumentNamesRU.add("Мелодический барабан");
        instrumentNamesRU.add("Синтетический барабан");
        instrumentNamesRU.add("Реверсивная тарелка");
        instrumentNamesRU.add("Звук ладов гитары");
        instrumentNamesRU.add("Дыхание");
        instrumentNamesRU.add("Морской прибой");
        instrumentNamesRU.add("Птичий свист");
        instrumentNamesRU.add("Телефонный звонок");
        instrumentNamesRU.add("Вертолет");
        instrumentNamesRU.add("Аплодисменты");
        instrumentNamesRU.add("Выстрел");
        //ударные
        instrumentNamesRU.add("Большой барабан 2");
        instrumentNamesRU.add("Большой барабан 1");
        instrumentNamesRU.add("Удар по краю барабана");
        instrumentNamesRU.add("Малый барабан 1");
        instrumentNamesRU.add("Хлопок в ладоши");
        instrumentNamesRU.add("Малый барабан 2");
        instrumentNamesRU.add("Низкий том 2");
        instrumentNamesRU.add("Закрытый Хай-хет");
        instrumentNamesRU.add("Низкий том 1");
        instrumentNamesRU.add("Педальный Хай-хет");
        instrumentNamesRU.add("Средний том 2");
        instrumentNamesRU.add("Открытый Хай-хет");
        instrumentNamesRU.add("Средний том 1");
        instrumentNamesRU.add("Высокий том 2");
        instrumentNamesRU.add("Тарелка краш 1");
        instrumentNamesRU.add("Высокий том 1");
        instrumentNamesRU.add("Тарелка райд 1");
        instrumentNamesRU.add("Китайская тарелка");
        instrumentNamesRU.add("Колокольчик райд");
        instrumentNamesRU.add("Тамбурин (бубен)");
        instrumentNamesRU.add("Тарелка сплэш");
        instrumentNamesRU.add("Коровий колокольчик");
        instrumentNamesRU.add("Тарелка крэш 2");
        instrumentNamesRU.add("Вибрирующий хлопок");
        instrumentNamesRU.add("Тарелка райд 2");
        instrumentNamesRU.add("Бонго высокий");
        instrumentNamesRU.add("Бонго низкий");
        instrumentNamesRU.add("Конго высокий глухой");
        instrumentNamesRU.add("Конго открытый высокий");
        instrumentNamesRU.add("Конго низкий");
        instrumentNamesRU.add("Литавры высокие");
        instrumentNamesRU.add("Литавры низкие");
        instrumentNamesRU.add("Агого высокий");
        instrumentNamesRU.add("Агого низкий");
        instrumentNamesRU.add("Кабаса");
        instrumentNamesRU.add("Маракас");
        instrumentNamesRU.add("Короткий свист");
        instrumentNamesRU.add("длинный свист");
        instrumentNamesRU.add("Гуиро короткий");
        instrumentNamesRU.add("Гуиро длинный");
        instrumentNamesRU.add("Клавес");
        instrumentNamesRU.add("Высокая деревянная коробка");
        instrumentNamesRU.add("Низкая деревянная коробка");
        instrumentNamesRU.add("Приглушенная куика");
        instrumentNamesRU.add("Открытая куика");
        instrumentNamesRU.add("Приглушенный треугольник");
        instrumentNamesRU.add("Открытый треугольник");

        instrumentNamesENG = new ArrayList<>();
        instrumentNamesENG.add("");
        instrumentNamesENG.add("Acoustic piano");
        instrumentNamesENG.add("Bright piano");
        instrumentNamesENG.add("Grand piano");
        instrumentNamesENG.add("Honky-tonk piano");
        instrumentNamesENG.add("Rhodes piano1");
        instrumentNamesENG.add("Chorused piano2");
        instrumentNamesENG.add("Harpsichord");
        instrumentNamesENG.add("Clavinet");
        instrumentNamesENG.add("Celesta");
        instrumentNamesENG.add("Glockenspiel");
        instrumentNamesENG.add("Music Box");
        instrumentNamesENG.add("Vibraphone");
        instrumentNamesENG.add("Marimba");
        instrumentNamesENG.add("Xylophone");
        instrumentNamesENG.add("Tubular Bells");
        instrumentNamesENG.add("Dulcimer");
        instrumentNamesENG.add("Hammmond");
        instrumentNamesENG.add("Percussive Organ");
        instrumentNamesENG.add("Rock Organ");
        instrumentNamesENG.add("Church Organ");
        instrumentNamesENG.add("Reed Organ");
        instrumentNamesENG.add("Accordion");
        instrumentNamesENG.add("Harmonica");
        instrumentNamesENG.add("Tango accordion");
        instrumentNamesENG.add("Nylon Guitar");
        instrumentNamesENG.add("Steel Guitar");
        instrumentNamesENG.add("Jazz Guitar");
        instrumentNamesENG.add("Clean Guitar");
        instrumentNamesENG.add("Muted Guitar");
        instrumentNamesENG.add("Overdriven Guitar");
        instrumentNamesENG.add("Distortion Guitar");
        instrumentNamesENG.add("Guitar Harmonics");
        instrumentNamesENG.add("Acoustiс Bass");
        instrumentNamesENG.add("Finger Bass");
        instrumentNamesENG.add("Piked Bass");
        instrumentNamesENG.add("Fretless Bass");
        instrumentNamesENG.add("Slap Bass 1");
        instrumentNamesENG.add("Slap Bass 2");
        instrumentNamesENG.add("Synth Bass 1");
        instrumentNamesENG.add("Synth Bass 2");
        instrumentNamesENG.add("Violin");
        instrumentNamesENG.add("Viola");
        instrumentNamesENG.add("Cello");
        instrumentNamesENG.add("Double Bass");
        instrumentNamesENG.add("Tremolo Strings");
        instrumentNamesENG.add("Pizzicato Strings");
        instrumentNamesENG.add("Orchestral Harp");
        instrumentNamesENG.add("Timpani");
        instrumentNamesENG.add("Strings 1");
        instrumentNamesENG.add("Strings 2");
        instrumentNamesENG.add("Synth Strings 1");
        instrumentNamesENG.add("Synth Strings 2");
        instrumentNamesENG.add("Choir Aahs");
        instrumentNamesENG.add("Voice oohs");
        instrumentNamesENG.add("Synth Voice");
        instrumentNamesENG.add("Orchestra Hit");
        instrumentNamesENG.add("Trumpet");
        instrumentNamesENG.add("Trombone");
        instrumentNamesENG.add("Tuba");
        instrumentNamesENG.add("Muted Trumpet");
        instrumentNamesENG.add("French Horn");
        instrumentNamesENG.add("Brass");
        instrumentNamesENG.add("Synth Brass 1");
        instrumentNamesENG.add("Synth Brass 2");
        instrumentNamesENG.add("Soprano Sax");
        instrumentNamesENG.add("Alto Sax");
        instrumentNamesENG.add("Tenor Sax");
        instrumentNamesENG.add("Baritone Sax");
        instrumentNamesENG.add("Oboe");
        instrumentNamesENG.add("English Horn");
        instrumentNamesENG.add("Bassoon");
        instrumentNamesENG.add("Clarinet");
        instrumentNamesENG.add("Piccolo");
        instrumentNamesENG.add("Flute");
        instrumentNamesENG.add("Recorder");
        instrumentNamesENG.add("Pan Flute");
        instrumentNamesENG.add("Bottle Blow");
        instrumentNamesENG.add("Shakuhachi");
        instrumentNamesENG.add("Whistle");
        instrumentNamesENG.add("Osarina");
        instrumentNamesENG.add("Square Wave");
        instrumentNamesENG.add("Sawtooth");
        instrumentNamesENG.add("Calliope");
        instrumentNamesENG.add("Chiff Lead");
        instrumentNamesENG.add("Charang");
        instrumentNamesENG.add("Solo Synth Lead");
        instrumentNamesENG.add("Bright Saw");
        instrumentNamesENG.add("Bass Lead");
        instrumentNamesENG.add("Fantasia");
        instrumentNamesENG.add("Warm Pad");
        instrumentNamesENG.add("Poly Synth");
        instrumentNamesENG.add("Space Pad");
        instrumentNamesENG.add("Bowed Glass");
        instrumentNamesENG.add("Metall");
        instrumentNamesENG.add("Halo Pad");
        instrumentNamesENG.add("Sweep Pad");
        instrumentNamesENG.add("Ice rain");
        instrumentNamesENG.add("Soundtrack");
        instrumentNamesENG.add("Crystal");
        instrumentNamesENG.add("Atmosphere");
        instrumentNamesENG.add("Brightness");
        instrumentNamesENG.add("Goblin");
        instrumentNamesENG.add("Echo theme");
        instrumentNamesENG.add("Star theme");
        instrumentNamesENG.add("Sitar");
        instrumentNamesENG.add("Banjo");
        instrumentNamesENG.add("Shamisen");
        instrumentNamesENG.add("Koto");
        instrumentNamesENG.add("Kalimba");
        instrumentNamesENG.add("Bagpipe");
        instrumentNamesENG.add("Fiddle");
        instrumentNamesENG.add("Shanai");
        instrumentNamesENG.add("Tinkle Bell");
        instrumentNamesENG.add("Agogo");
        instrumentNamesENG.add("Steel Drums");
        instrumentNamesENG.add("Woodblock");
        instrumentNamesENG.add("Taiko Drum");
        instrumentNamesENG.add("Melodic Drum");
        instrumentNamesENG.add("Synth Drum");
        instrumentNamesENG.add("Reverse Cymbal");
        instrumentNamesENG.add("Guitar Fret");
        instrumentNamesENG.add("Breath");
        instrumentNamesENG.add("Seashore");
        instrumentNamesENG.add("Bird Tweet");
        instrumentNamesENG.add("Telephone Ring");
        instrumentNamesENG.add("Helicopter");
        instrumentNamesENG.add("Applause");
        instrumentNamesENG.add("Gunshot");
        //ударные
        instrumentNamesENG.add("Bass Drum 2");
        instrumentNamesENG.add("Bass Drum 1");
        instrumentNamesENG.add("Side Stick");
        instrumentNamesENG.add("Snare Drum 1");
        instrumentNamesENG.add("Hand Clap");
        instrumentNamesENG.add("Snare Drum 2");
        instrumentNamesENG.add("Low Tom 2");
        instrumentNamesENG.add("Closed Hi-hat");
        instrumentNamesENG.add("Low Tom 1");
        instrumentNamesENG.add("Pedal Hi- hat");
        instrumentNamesENG.add("Mid Tom 2");
        instrumentNamesENG.add("Open Hi-hat");
        instrumentNamesENG.add("Mid Tom 1");
        instrumentNamesENG.add("High Tom 2");
        instrumentNamesENG.add("Crash Cymbal 1");
        instrumentNamesENG.add("High Tom 1");
        instrumentNamesENG.add("Ride Cymbal 1");
        instrumentNamesENG.add("Chinese Cymbal");
        instrumentNamesENG.add("Ride Bell");
        instrumentNamesENG.add("Tambourine");
        instrumentNamesENG.add("Splash Cymbal");
        instrumentNamesENG.add("Cowbell");
        instrumentNamesENG.add("Crash Cymbal 2");
        instrumentNamesENG.add("Vibra Slap");
        instrumentNamesENG.add("Ride Cymbal 2");
        instrumentNamesENG.add("High Bongo");
        instrumentNamesENG.add("Low Bongo");
        instrumentNamesENG.add("Mute High Conga");
        instrumentNamesENG.add("Open High Conga");
        instrumentNamesENG.add("Low Conga");
        instrumentNamesENG.add("High Timbale");
        instrumentNamesENG.add("Low Timbale");
        instrumentNamesENG.add("High Agogo");
        instrumentNamesENG.add("Low Agogo");
        instrumentNamesENG.add("Cabasa");
        instrumentNamesENG.add("Maracas");
        instrumentNamesENG.add("Short Whistle");
        instrumentNamesENG.add("Long Whistle");
        instrumentNamesENG.add("Short Guiro");
        instrumentNamesENG.add("Long Guiro");
        instrumentNamesENG.add("Claves");
        instrumentNamesENG.add("High Wood Block");
        instrumentNamesENG.add("Low Wood Block");
        instrumentNamesENG.add("Mute Cuica");
        instrumentNamesENG.add("Open Cuica");
        instrumentNamesENG.add("Mute Triangle");
        instrumentNamesENG.add("Open Triangle");
    }

    public static String getNamesInstrumentRU(int instrumentNumber) {
        return instrumentNamesRU.get(instrumentNumber);
    }

    public static String getNamesInstrumentENG(int instrumentNumber) {
        return instrumentNamesENG.get(instrumentNumber);
    }

    public static int getMaximalInstrumentNumber() {
        return instrumentNamesENG.size();
    }
}
